apiVersion: batch/v1
kind: Job
metadata:
  name: t2mlr-{{ORX_RUN}}
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-RTX-PRO-6000-Blackwell-Server-Edition
      containers:
        - name: run
          image: pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime
          command: ["bash", "-c", "eval \"$ORX_SCRIPT\""]
          resources:
            requests:
              nvidia.com/gpu: "4"
              cpu: "32"
              memory: 200Gi
            limits:
              nvidia.com/gpu: "4"
              cpu: "60"
              memory: 450Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 64Gi
